
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!

def pods
    # ----------A----------
    pod 'AFNetworking',                     '~> 3.1.0'

    

    # ----------M----------
    pod 'Masonry',                          '~> 1.1.0'
    pod 'SVProgressHUD',                    '~> 2.2.2'


    # ----------P----------
    pod 'pop',                               '~> 1.0.10'

    
    pod 'FDStackView', '~> 1.0'


    # ----------S----------
    pod 'SDWebImage',                       '~> 4.2.2'

    # ----------X----------
    pod 'XYQuick',                          '~> 0.9.10'

    # ----------U----------
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'

    pod 'SGQRCode'
end

target 'ContractQuery' do
    pods
    
end
